version: "3.9"
services:
  balance:
    image: chrislusf/seaweedfs:3.67
    networks:
      - seaweedfs
    environment:
      SHELL_MASTER: seaweedfs_master:9333
    volumes:
      - /mnt/seaweedfs/seaweedfs/metabackup:/data
    command: 
      - "shell"
      - "lock;"
      - "volume.balance -force;"
      - "volume.fix.replication;"
      - "unlock"
    deploy:
      restart_policy:
        condition: none

networks:
  seaweedfs:
    external: true