version: "3.9"

networks:
  seaweedfs:
    external: true

configs:
  filer:
    file: ./filer.sh
  mount:
    file: ./mount.sh
  volume:
    file: ./volume.sh

x-filer: &filer
  image: chrislusf/seaweedfs:latest
  environment:
    - HOST={{.Node.Hostname}}
  entrypoint: /filer.sh
  networks:
    - seaweedfs
  volumes:
    - /mnt/seaweedfs/seaweedfs/filer:/data/filerdb
  configs:
    - source: filer
      target: /filer.sh
      mode: 755

x-volume: &volume
  image: chrislusf/seaweedfs:latest
  environment:
    - HOST={{.Node.Hostname}}
  entrypoint: /volume.sh
  networks:
    - seaweedfs
  volumes:
    - /mnt/seaweedfs/seaweedfs/volume:/data
  configs:
    - source: volume
      target: /volume.sh
      mode: 755

services:
  master:
    image: chrislusf/seaweedfs:latest
    command: 
      - "master"
      - "-defaultReplication=200"
      - "-volumeSizeLimitMB=408576"
      - "-garbageThreshold=0.01"
      - "-mdir=/data"
    networks:
      - seaweedfs
    volumes:
      - /mnt/seaweedfs/seaweedfs/master:/data
    deploy:
      placement:
        max_replicas_per_node: 1

  mount:
    image: docker:dind
    cap_add: 
      - SYS_ADMIN
    networks:
      - seaweedfs
    environment:
      - HOST={{.Node.Hostname}}
    volumes:
      - /mnt/seaweedfs:/mnt:rshared
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint: /mount.sh
    init: true
    stop_grace_period: 30s
    configs:
      - source: mount
        target: /mount.sh
        mode: 755
    deploy:
      mode: global

  cron: 
    image: chrislusf/seaweedfs:latest
    networks:
      - seaweedfs
    environment:
      SHELL_MASTER: seaweedfs_master:9333
    volumes:
      - /mnt/seaweedfs/seaweedfs/metabackup:/data
    command: 
      - "shell"
      - "lock;"
      - "volume.deleteEmpty -quietFor=24h -force;"
      - "volume.balance -force;"
      - "volume.fix.replication;"
      - "unlock"
    deploy:
      restart_policy:
        condition: none
      labels: 
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 3 * * *
        - swarm.cronjob.skip-running=true

  filer_tierra:
    <<: *filer
    deploy:
      placement:
        constraints:
          - "node.hostname == tierra"
  filer_mercurio:
    <<: *filer
    deploy:
      placement:
        constraints:
          - "node.hostname == mercurio"
  filer_venus:
    <<: *filer
    deploy:
      placement:
        constraints:
          - "node.hostname == venus"

  volume_tierra:
    <<: *volume
    deploy:
      placement:
        constraints:
          - "node.hostname == tierra"
  volume_mercurio:
    <<: *volume
    deploy:
      placement:
        constraints:
          - "node.hostname == mercurio"
  volume_venus:
    <<: *volume
    deploy:
      placement:
        constraints:
          - "node.hostname == venus"